[package]
name = "flint_bindings"
version = "3.3.0"
edition = "2021"
links = "flint"

[features]
build-gmp = ["dep:gmp-mpfr-sys"]
rerun-bindgen = ["dep:bindgen"]
use-system-flint = ["rerun-bindgen"]
use-system-gmp = []

[dependencies]
gmp-mpfr-sys = { version = "1.6.4", optional = true }

[build-dependencies]
anyhow = "1.0.98"
bindgen = { version = "0.71.1", optional = true }
cc = "1.2.23"
pkg-config = "0.3.32"

[profile.dev]
opt-level = 1
