/* automatically generated by rust-bindgen 0.72.1 */

pub use crate::ffi_prelude::*;

#[repr(C)]
pub struct __BindgenUnionField<T>(::std::marker::PhantomData<T>);
impl<T> __BindgenUnionField<T> {
    #[inline]
    pub const fn new() -> Self {
        __BindgenUnionField(::std::marker::PhantomData)
    }
    #[inline]
    pub unsafe fn as_ref(&self) -> &T {
        ::std::mem::transmute(self)
    }
    #[inline]
    pub unsafe fn as_mut(&mut self) -> &mut T {
        ::std::mem::transmute(self)
    }
}
impl<T> ::std::default::Default for __BindgenUnionField<T> {
    #[inline]
    fn default() -> Self {
        Self::new()
    }
}
impl<T> ::std::clone::Clone for __BindgenUnionField<T> {
    #[inline]
    fn clone(&self) -> Self {
        *self
    }
}
impl<T> ::std::marker::Copy for __BindgenUnionField<T> {}
impl<T> ::std::fmt::Debug for __BindgenUnionField<T> {
    fn fmt(&self, fmt: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        fmt.write_str("__BindgenUnionField")
    }
}
impl<T> ::std::hash::Hash for __BindgenUnionField<T> {
    fn hash<H: ::std::hash::Hasher>(&self, _state: &mut H) {}
}
impl<T> ::std::cmp::PartialEq for __BindgenUnionField<T> {
    fn eq(&self, _other: &__BindgenUnionField<T>) -> bool {
        true
    }
}
impl<T> ::std::cmp::Eq for __BindgenUnionField<T> {}
#[repr(C)]
pub struct __FLINT_FILE {
    _unused: [u8; 0],
}
pub type FLINT_FILE = __FLINT_FILE;
pub type ulong = ::std::os::raw::c_ulong;
pub type slong = ::std::os::raw::c_long;
pub type flint_bitcnt_t = ulong;
pub type nn_ptr = *mut ulong;
pub type nn_srcptr = *const ulong;
pub type flint_cleanup_function_t = ::std::option::Option<unsafe extern "C" fn()>;
pub type thread_pool_handle = ::std::os::raw::c_int;
#[repr(C)]
pub struct flint_rand_struct {
    pub __gmp_state: *mut ::std::os::raw::c_void,
    pub __randval: ulong,
    pub __randval2: ulong,
}
pub type flint_rand_t = [flint_rand_struct; 1usize];
pub const flint_err_t_FLINT_ERROR: flint_err_t = 0;
pub const flint_err_t_FLINT_OVERFLOW: flint_err_t = 1;
pub const flint_err_t_FLINT_IMPINV: flint_err_t = 2;
pub const flint_err_t_FLINT_DOMERR: flint_err_t = 3;
pub const flint_err_t_FLINT_DIVZERO: flint_err_t = 4;
pub const flint_err_t_FLINT_EXPOF: flint_err_t = 5;
pub const flint_err_t_FLINT_INEXACT: flint_err_t = 6;
pub const flint_err_t_FLINT_TEST_FAIL: flint_err_t = 7;
pub type flint_err_t = ::std::os::raw::c_uint;
#[repr(C)]
pub struct nmod_t {
    pub n: ulong,
    pub ninv: ulong,
    pub norm: flint_bitcnt_t,
}
pub type fmpz = slong;
pub type fmpz_t = [fmpz; 1usize];
#[repr(C)]
pub struct fmpq {
    pub num: fmpz,
    pub den: fmpz,
}
pub type fmpq_t = [fmpq; 1usize];
#[repr(C)]
pub struct mantissa_noptr_struct {
    pub d: [ulong; 2usize],
}
#[repr(C)]
pub struct mantissa_ptr_struct {
    pub alloc: slong,
    pub d: nn_ptr,
}
#[repr(C)]
pub struct mantissa_struct {
    pub noptr: __BindgenUnionField<mantissa_noptr_struct>,
    pub ptr: __BindgenUnionField<mantissa_ptr_struct>,
    pub bindgen_union_field: [u64; 2usize],
}
#[repr(C)]
pub struct arf_struct {
    pub exp: fmpz,
    pub size: slong,
    pub d: mantissa_struct,
}
pub type arf_t = [arf_struct; 1usize];
pub type arf_ptr = *mut arf_struct;
pub type arf_srcptr = *const arf_struct;
#[repr(C)]
pub struct arf_interval_struct {
    pub a: arf_struct,
    pub b: arf_struct,
}
pub type arf_interval_t = [arf_interval_struct; 1usize];
pub type arf_interval_ptr = *mut arf_interval_struct;
pub type arf_interval_srcptr = *const arf_interval_struct;
#[repr(C)]
pub struct mag_struct {
    pub exp: fmpz,
    pub man: ulong,
}
pub type mag_t = [mag_struct; 1usize];
pub type mag_ptr = *mut mag_struct;
pub type mag_srcptr = *const mag_struct;
#[repr(C)]
pub struct arb_struct {
    pub mid: arf_struct,
    pub rad: mag_struct,
}
pub type arb_t = [arb_struct; 1usize];
pub type arb_ptr = *mut arb_struct;
pub type arb_srcptr = *const arb_struct;
#[repr(C)]
pub struct arb_mat_struct {
    pub entries: arb_ptr,
    pub r: slong,
    pub c: slong,
    pub stride: slong,
}
pub type arb_mat_t = [arb_mat_struct; 1usize];
#[repr(C)]
pub struct arb_poly_struct {
    pub coeffs: arb_ptr,
    pub alloc: slong,
    pub length: slong,
}
pub type arb_poly_t = [arb_poly_struct; 1usize];
#[repr(C)]
pub struct acb_struct {
    pub real: arb_struct,
    pub imag: arb_struct,
}
pub type acb_t = [acb_struct; 1usize];
pub type acb_ptr = *mut acb_struct;
pub type acb_srcptr = *const acb_struct;
#[repr(C)]
pub struct acb_mat_struct {
    pub entries: acb_ptr,
    pub r: slong,
    pub c: slong,
    pub stride: slong,
}
pub type acb_mat_t = [acb_mat_struct; 1usize];
#[repr(C)]
pub struct acb_poly_struct {
    pub coeffs: acb_ptr,
    pub alloc: slong,
    pub length: slong,
}
pub type acb_poly_t = [acb_poly_struct; 1usize];
#[repr(C)]
pub struct acf_struct {
    pub real: arf_struct,
    pub imag: arf_struct,
}
pub type acf_t = [acf_struct; 1usize];
pub type acf_ptr = *mut acf_struct;
pub type acf_srcptr = *const acf_struct;
pub const truth_t_T_TRUE: truth_t = 0;
pub const truth_t_T_FALSE: truth_t = 1;
pub const truth_t_T_UNKNOWN: truth_t = 2;
pub type truth_t = ::std::os::raw::c_uint;
#[repr(C)]
pub struct gr_stream_struct {
    pub fp: *mut FLINT_FILE,
    pub s: *mut ::std::os::raw::c_char,
    pub len: slong,
    pub alloc: slong,
}
pub type gr_stream_t = [gr_stream_struct; 1usize];
pub type gr_funcptr = ::std::option::Option<
    unsafe extern "C" fn() -> ::std::os::raw::c_int,
>;
#[repr(C)]
pub struct gr_ctx_struct {
    pub data: [::std::os::raw::c_char; 48usize],
    pub which_ring: ulong,
    pub sizeof_elem: slong,
    pub methods: *mut gr_funcptr,
    pub size_limit: ulong,
}
pub type gr_ctx_t = [gr_ctx_struct; 1usize];
pub type gr_ptr = *mut ::std::os::raw::c_void;
pub type gr_srcptr = *const ::std::os::raw::c_void;
pub type gr_ctx_ptr = *mut ::std::os::raw::c_void;
#[repr(C)]
pub struct gr_vec_struct {
    pub entries: gr_ptr,
    pub alloc: slong,
    pub length: slong,
}
pub type gr_vec_t = [gr_vec_struct; 1usize];
#[repr(C)]
pub struct gr_mat_struct {
    pub entries: gr_ptr,
    pub r: slong,
    pub c: slong,
    pub stride: slong,
}
pub type gr_mat_t = [gr_mat_struct; 1usize];
#[repr(C)]
pub struct gr_poly_struct {
    pub coeffs: gr_ptr,
    pub alloc: slong,
    pub length: slong,
}
pub type gr_poly_t = [gr_poly_struct; 1usize];
#[repr(C)]
pub struct zz_struct {
    pub alloc: ::std::os::raw::c_int,
    pub size: ::std::os::raw::c_int,
    pub ptr: nn_ptr,
}
pub type zz_ptr = *mut zz_struct;
pub type zz_srcptr = *const zz_struct;
#[repr(C)]
pub struct fmpz_factor_struct {
    pub sign: ::std::os::raw::c_int,
    pub p: *mut fmpz,
    pub exp: *mut ulong,
    pub alloc: slong,
    pub num: slong,
}
pub type fmpz_factor_t = [fmpz_factor_struct; 1usize];
#[repr(C)]
pub struct fmpz_preinvn_struct {
    pub dinv: nn_ptr,
    pub n: slong,
    pub norm: flint_bitcnt_t,
}
pub type fmpz_preinvn_t = [fmpz_preinvn_struct; 1usize];
#[repr(C)]
pub struct fmpz_poly_struct {
    pub coeffs: *mut fmpz,
    pub alloc: slong,
    pub length: slong,
}
pub type fmpz_poly_t = [fmpz_poly_struct; 1usize];
#[repr(C)]
pub struct fmpz_poly_factor_struct {
    pub c: fmpz,
    pub p: *mut fmpz_poly_struct,
    pub exp: *mut slong,
    pub num: slong,
    pub alloc: slong,
}
pub type fmpz_poly_factor_t = [fmpz_poly_factor_struct; 1usize];
#[repr(C)]
pub struct fmpz_mat_struct {
    pub entries: *mut fmpz,
    pub r: slong,
    pub c: slong,
    pub stride: slong,
}
pub type fmpz_mat_t = [fmpz_mat_struct; 1usize];
#[repr(C)]
pub struct fmpz_poly_mat_struct {
    pub entries: *mut fmpz_poly_struct,
    pub r: slong,
    pub c: slong,
    pub stride: slong,
}
pub type fmpz_poly_mat_t = [fmpz_poly_mat_struct; 1usize];
#[repr(C)]
pub struct fmpz_mpoly_struct {
    pub coeffs: *mut fmpz,
    pub exps: *mut ulong,
    pub alloc: slong,
    pub length: slong,
    pub bits: flint_bitcnt_t,
}
pub type fmpz_mpoly_t = [fmpz_mpoly_struct; 1usize];
#[repr(C)]
pub struct fmpz_mpoly_factor_struct {
    pub constant: fmpz_t,
    pub constant_den: fmpz_t,
    pub poly: *mut fmpz_mpoly_struct,
    pub exp: *mut fmpz,
    pub num: slong,
    pub alloc: slong,
}
pub type fmpz_mpoly_factor_t = [fmpz_mpoly_factor_struct; 1usize];
#[repr(C)]
pub struct fmpz_poly_q_struct {
    pub num: *mut fmpz_poly_struct,
    pub den: *mut fmpz_poly_struct,
}
pub type fmpz_poly_q_t = [fmpz_poly_q_struct; 1usize];
#[repr(C)]
pub struct fmpz_mpoly_q_struct {
    pub num: fmpz_mpoly_struct,
    pub den: fmpz_mpoly_struct,
}
pub type fmpz_mpoly_q_t = [fmpz_mpoly_q_struct; 1usize];
#[repr(C)]
pub struct fmpzi_struct {
    pub a: fmpz,
    pub b: fmpz,
}
pub type fmpzi_t = [fmpzi_struct; 1usize];
#[repr(C)]
pub struct fmpz_mod_ctx {
    pub n: fmpz_t,
    pub add_fxn: ::std::option::Option<
        unsafe extern "C" fn(
            arg1: *mut fmpz,
            arg2: *const fmpz,
            arg3: *const fmpz,
            arg4: *const fmpz_mod_ctx,
        ),
    >,
    pub sub_fxn: ::std::option::Option<
        unsafe extern "C" fn(
            arg1: *mut fmpz,
            arg2: *const fmpz,
            arg3: *const fmpz,
            arg4: *const fmpz_mod_ctx,
        ),
    >,
    pub mul_fxn: ::std::option::Option<
        unsafe extern "C" fn(
            arg1: *mut fmpz,
            arg2: *const fmpz,
            arg3: *const fmpz,
            arg4: *const fmpz_mod_ctx,
        ),
    >,
    pub mod_: nmod_t,
    pub n_limbs: [ulong; 3usize],
    pub ninv_limbs: [ulong; 3usize],
    pub ninv_huge: *mut fmpz_preinvn_struct,
}
pub type fmpz_mod_ctx_struct = fmpz_mod_ctx;
pub type fmpz_mod_ctx_t = [fmpz_mod_ctx_struct; 1usize];
pub type fmpz_mod_mat_struct = fmpz_mat_struct;
pub type fmpz_mod_mat_t = [fmpz_mod_mat_struct; 1usize];
#[repr(C)]
pub struct fmpz_mod_poly_struct {
    pub coeffs: *mut fmpz,
    pub alloc: slong,
    pub length: slong,
}
pub type fmpz_mod_poly_t = [fmpz_mod_poly_struct; 1usize];
#[repr(C)]
pub struct fmpz_mod_poly_factor_struct {
    pub poly: *mut fmpz_mod_poly_struct,
    pub exp: *mut slong,
    pub num: slong,
    pub alloc: slong,
}
pub type fmpz_mod_poly_factor_t = [fmpz_mod_poly_factor_struct; 1usize];
#[repr(C)]
pub struct fmpz_mod_mpoly_struct {
    pub coeffs: *mut fmpz,
    pub exps: *mut ulong,
    pub length: slong,
    pub bits: flint_bitcnt_t,
    pub coeffs_alloc: slong,
    pub exps_alloc: slong,
}
pub type fmpz_mod_mpoly_t = [fmpz_mod_mpoly_struct; 1usize];
#[repr(C)]
pub struct fmpz_mod_mpoly_factor_struct {
    pub constant: fmpz_t,
    pub poly: *mut fmpz_mod_mpoly_struct,
    pub exp: *mut fmpz,
    pub num: slong,
    pub alloc: slong,
}
pub type fmpz_mod_mpoly_factor_t = [fmpz_mod_mpoly_factor_struct; 1usize];
#[repr(C)]
pub struct fmpz_mod_mpoly_q_struct {
    pub num: fmpz_mod_mpoly_struct,
    pub den: fmpz_mod_mpoly_struct,
}
pub type fmpz_mod_mpoly_q_t = [fmpz_mod_mpoly_q_struct; 1usize];
#[repr(C)]
pub struct nmod_mat_struct {
    pub entries: *mut ulong,
    pub r: slong,
    pub c: slong,
    pub stride: slong,
    pub mod_: nmod_t,
}
pub type nmod_mat_t = [nmod_mat_struct; 1usize];
#[repr(C)]
pub struct nmod_poly_struct {
    pub coeffs: nn_ptr,
    pub alloc: slong,
    pub length: slong,
    pub mod_: nmod_t,
}
pub type nmod_poly_t = [nmod_poly_struct; 1usize];
#[repr(C)]
pub struct nmod_poly_factor_struct {
    pub p: *mut nmod_poly_struct,
    pub exp: *mut slong,
    pub num: slong,
    pub alloc: slong,
}
pub type nmod_poly_factor_t = [nmod_poly_factor_struct; 1usize];
#[repr(C)]
pub struct nmod_poly_mat_struct {
    pub entries: *mut nmod_poly_struct,
    pub r: slong,
    pub c: slong,
    pub stride: slong,
    pub modulus: ulong,
}
pub type nmod_poly_mat_t = [nmod_poly_mat_struct; 1usize];
#[repr(C)]
pub struct nmod_mpoly_struct {
    pub coeffs: *mut ulong,
    pub exps: *mut ulong,
    pub length: slong,
    pub bits: flint_bitcnt_t,
    pub coeffs_alloc: slong,
    pub exps_alloc: slong,
}
pub type nmod_mpoly_t = [nmod_mpoly_struct; 1usize];
#[repr(C)]
pub struct nmod_mpoly_factor_struct {
    pub constant: ulong,
    pub poly: *mut nmod_mpoly_struct,
    pub exp: *mut fmpz,
    pub num: slong,
    pub alloc: slong,
}
pub type nmod_mpoly_factor_t = [nmod_mpoly_factor_struct; 1usize];
pub const dot_method_t__DOT0: dot_method_t = 0;
pub const dot_method_t__DOT1: dot_method_t = 1;
pub const dot_method_t__DOT2_SPLIT: dot_method_t = 2;
pub const dot_method_t__DOT2_HALF: dot_method_t = 3;
pub const dot_method_t__DOT2: dot_method_t = 4;
pub const dot_method_t__DOT3_ACC: dot_method_t = 5;
pub const dot_method_t__DOT3: dot_method_t = 6;
pub const dot_method_t__DOT_POW2: dot_method_t = 7;
pub type dot_method_t = ::std::os::raw::c_uint;
#[repr(C)]
pub struct dot_params_t {
    pub method: dot_method_t,
    pub pow2_precomp: ulong,
}
pub type fq_nmod_t = nmod_poly_t;
pub type fq_nmod_struct = nmod_poly_struct;
#[repr(C)]
pub struct fq_nmod_ctx_struct {
    pub mod_: nmod_t,
    pub sparse_modulus: ::std::os::raw::c_int,
    pub is_conway: ::std::os::raw::c_int,
    pub a: *mut ulong,
    pub j: *mut slong,
    pub len: slong,
    pub modulus: nmod_poly_t,
    pub inv: nmod_poly_t,
    pub var: *mut ::std::os::raw::c_char,
}
pub type fq_nmod_ctx_t = [fq_nmod_ctx_struct; 1usize];
#[repr(C)]
pub struct fq_nmod_mat_struct {
    pub entries: *mut fq_nmod_struct,
    pub r: slong,
    pub c: slong,
    pub stride: slong,
}
pub type fq_nmod_mat_t = [fq_nmod_mat_struct; 1usize];
#[repr(C)]
pub struct fq_nmod_poly_struct {
    pub coeffs: *mut fq_nmod_struct,
    pub alloc: slong,
    pub length: slong,
}
pub type fq_nmod_poly_t = [fq_nmod_poly_struct; 1usize];
#[repr(C)]
pub struct fq_nmod_poly_factor_struct {
    pub poly: *mut fq_nmod_poly_struct,
    pub exp: *mut slong,
    pub num: slong,
    pub alloc: slong,
}
pub type fq_nmod_poly_factor_t = [fq_nmod_poly_factor_struct; 1usize];
#[repr(C)]
pub struct fq_nmod_mpoly_struct {
    pub coeffs: *mut ulong,
    pub exps: *mut ulong,
    pub length: slong,
    pub bits: flint_bitcnt_t,
    pub coeffs_alloc: slong,
    pub exps_alloc: slong,
}
pub type fq_nmod_mpoly_t = [fq_nmod_mpoly_struct; 1usize];
#[repr(C)]
pub struct n_poly_struct {
    pub coeffs: *mut ulong,
    pub alloc: slong,
    pub length: slong,
}
pub type n_poly_t = [n_poly_struct; 1usize];
pub type n_fq_poly_struct = n_poly_struct;
pub type n_fq_poly_t = n_poly_t;
#[repr(C)]
pub struct n_bpoly_struct {
    pub coeffs: *mut n_poly_struct,
    pub alloc: slong,
    pub length: slong,
}
pub type n_bpoly_t = [n_bpoly_struct; 1usize];
pub type n_fq_bpoly_struct = n_bpoly_struct;
pub type n_fq_bpoly_t = n_bpoly_t;
#[repr(C)]
pub struct n_tpoly_struct {
    pub coeffs: *mut n_bpoly_struct,
    pub alloc: slong,
    pub length: slong,
}
pub type n_tpoly_t = [n_tpoly_struct; 1usize];
pub type n_fq_tpoly_struct = n_tpoly_struct;
pub type n_fq_tpoly_t = n_tpoly_t;
#[repr(C)]
pub struct n_polyu_struct {
    pub exps: *mut ulong,
    pub coeffs: *mut ulong,
    pub length: slong,
    pub alloc: slong,
}
pub type n_polyu_t = [n_polyu_struct; 1usize];
pub type n_fq_polyu_struct = n_polyu_struct;
pub type n_fq_polyu_t = n_polyu_t;
#[repr(C)]
pub struct n_polyun_struct {
    pub coeffs: *mut n_poly_struct,
    pub exps: *mut ulong,
    pub length: slong,
    pub alloc: slong,
}
pub type n_polyun_t = [n_polyun_struct; 1usize];
pub type n_fq_polyun_struct = n_polyun_struct;
pub type n_fq_polyun_t = n_polyun_t;
#[repr(C)]
pub struct n_poly_stack_struct {
    pub array: *mut *mut n_poly_struct,
    pub alloc: slong,
    pub top: slong,
}
pub type n_poly_stack_t = [n_poly_stack_struct; 1usize];
#[repr(C)]
pub struct n_bpoly_stack_struct {
    pub array: *mut *mut n_bpoly_struct,
    pub alloc: slong,
    pub top: slong,
}
pub type n_bpoly_stack_t = [n_bpoly_stack_struct; 1usize];
#[repr(C)]
pub struct n_poly_bpoly_stack_struct {
    pub poly_stack: n_poly_stack_t,
    pub bpoly_stack: n_bpoly_stack_t,
}
pub type n_poly_bpoly_stack_t = [n_poly_bpoly_stack_struct; 1usize];
#[repr(C)]
pub struct nmod_eval_interp_struct {
    pub M: *mut ulong,
    pub T: *mut ulong,
    pub Q: *mut ulong,
    pub array: *mut ulong,
    pub alloc: slong,
    pub d: slong,
    pub radix: slong,
    pub w: ulong,
}
pub type nmod_eval_interp_t = [nmod_eval_interp_struct; 1usize];
pub const ordering_t_ORD_LEX: ordering_t = 0;
pub const ordering_t_ORD_DEGLEX: ordering_t = 1;
pub const ordering_t_ORD_DEGREVLEX: ordering_t = 2;
pub type ordering_t = ::std::os::raw::c_uint;
#[repr(C)]
pub struct mpoly_ctx_struct {
    pub nvars: slong,
    pub nfields: slong,
    pub ord: ordering_t,
    pub deg: ::std::os::raw::c_int,
    pub rev: ::std::os::raw::c_int,
    pub lut_words_per_exp: [slong; 64usize],
    pub lut_fix_bits: [::std::os::raw::c_uchar; 64usize],
}
pub type mpoly_ctx_t = [mpoly_ctx_struct; 1usize];
#[repr(C)]
pub struct nmod_mpoly_ctx_struct {
    pub minfo: mpoly_ctx_t,
    pub mod_: nmod_t,
}
pub type nmod_mpoly_ctx_t = [nmod_mpoly_ctx_struct; 1usize];
#[repr(C)]
pub struct fmpz_mpoly_ctx_struct {
    pub minfo: mpoly_ctx_t,
}
pub type fmpz_mpoly_ctx_t = [fmpz_mpoly_ctx_struct; 1usize];
#[repr(C)]
pub struct fmpq_mpoly_ctx_struct {
    pub zctx: fmpz_mpoly_ctx_t,
}
pub type fmpq_mpoly_ctx_t = [fmpq_mpoly_ctx_struct; 1usize];
#[repr(C)]
pub struct fmpz_mod_mpoly_ctx_struct {
    pub minfo: mpoly_ctx_t,
    pub ffinfo: fmpz_mod_ctx_t,
}
pub type fmpz_mod_mpoly_ctx_t = [fmpz_mod_mpoly_ctx_struct; 1usize];
#[repr(C)]
pub struct fq_nmod_mpoly_ctx_struct {
    pub minfo: mpoly_ctx_t,
    pub fqctx: fq_nmod_ctx_t,
}
pub type fq_nmod_mpoly_ctx_t = [fq_nmod_mpoly_ctx_struct; 1usize];
#[repr(C)]
pub struct _bindgen_ty_2 {
    pub elem_size: slong,
    pub ctx: *const ::std::os::raw::c_void,
    pub init: ::std::option::Option<
        unsafe extern "C" fn(
            arg1: *mut ::std::os::raw::c_void,
            arg2: *const ::std::os::raw::c_void,
        ),
    >,
    pub clear: ::std::option::Option<
        unsafe extern "C" fn(
            arg1: *mut ::std::os::raw::c_void,
            arg2: *const ::std::os::raw::c_void,
        ),
    >,
    pub is_zero: ::std::option::Option<
        unsafe extern "C" fn(
            arg1: *const ::std::os::raw::c_void,
            arg2: *const ::std::os::raw::c_void,
        ) -> ::std::os::raw::c_int,
    >,
    pub zero: ::std::option::Option<
        unsafe extern "C" fn(
            arg1: *mut ::std::os::raw::c_void,
            arg2: *const ::std::os::raw::c_void,
        ),
    >,
    pub one: ::std::option::Option<
        unsafe extern "C" fn(
            arg1: *mut ::std::os::raw::c_void,
            arg2: *const ::std::os::raw::c_void,
        ),
    >,
    pub set_fmpz: ::std::option::Option<
        unsafe extern "C" fn(
            arg1: *mut ::std::os::raw::c_void,
            arg2: *const fmpz,
            arg3: *const ::std::os::raw::c_void,
        ),
    >,
    pub set: ::std::option::Option<
        unsafe extern "C" fn(
            arg1: *mut ::std::os::raw::c_void,
            arg2: *const ::std::os::raw::c_void,
            arg3: *const ::std::os::raw::c_void,
        ),
    >,
    pub swap: ::std::option::Option<
        unsafe extern "C" fn(
            arg1: *mut ::std::os::raw::c_void,
            arg2: *mut ::std::os::raw::c_void,
            arg3: *const ::std::os::raw::c_void,
        ),
    >,
    pub neg: ::std::option::Option<
        unsafe extern "C" fn(
            arg1: *mut ::std::os::raw::c_void,
            arg2: *const ::std::os::raw::c_void,
            arg3: *const ::std::os::raw::c_void,
        ),
    >,
    pub add: ::std::option::Option<
        unsafe extern "C" fn(
            arg1: *mut ::std::os::raw::c_void,
            arg2: *const ::std::os::raw::c_void,
            arg3: *const ::std::os::raw::c_void,
            arg4: *const ::std::os::raw::c_void,
        ),
    >,
    pub sub: ::std::option::Option<
        unsafe extern "C" fn(
            arg1: *mut ::std::os::raw::c_void,
            arg2: *const ::std::os::raw::c_void,
            arg3: *const ::std::os::raw::c_void,
            arg4: *const ::std::os::raw::c_void,
        ),
    >,
    pub mul_fmpz: ::std::option::Option<
        unsafe extern "C" fn(
            arg1: *mut ::std::os::raw::c_void,
            arg2: *const ::std::os::raw::c_void,
            arg3: *const fmpz,
            arg4: *const ::std::os::raw::c_void,
        ),
    >,
    pub mul: ::std::option::Option<
        unsafe extern "C" fn(
            arg1: *mut ::std::os::raw::c_void,
            arg2: *const ::std::os::raw::c_void,
            arg3: *const ::std::os::raw::c_void,
            arg4: *const ::std::os::raw::c_void,
        ),
    >,
    pub divexact: ::std::option::Option<
        unsafe extern "C" fn(
            arg1: *mut ::std::os::raw::c_void,
            arg2: *const ::std::os::raw::c_void,
            arg3: *const ::std::os::raw::c_void,
            arg4: *const ::std::os::raw::c_void,
        ),
    >,
    pub divides: ::std::option::Option<
        unsafe extern "C" fn(
            arg1: *mut ::std::os::raw::c_void,
            arg2: *const ::std::os::raw::c_void,
            arg3: *const ::std::os::raw::c_void,
            arg4: *const ::std::os::raw::c_void,
        ) -> ::std::os::raw::c_int,
    >,
    pub pow_fmpz: ::std::option::Option<
        unsafe extern "C" fn(
            arg1: *mut ::std::os::raw::c_void,
            arg2: *const ::std::os::raw::c_void,
            arg3: *const fmpz,
            arg4: *const ::std::os::raw::c_void,
        ) -> ::std::os::raw::c_int,
    >,
    pub length: ::std::option::Option<
        unsafe extern "C" fn(
            arg1: *const ::std::os::raw::c_void,
            arg2: *const ::std::os::raw::c_void,
        ) -> slong,
    >,
}
pub type mpoly_void_ring_t = [_bindgen_ty_2; 1usize];
#[repr(C)]
pub struct mpoly_gcd_info_struct {
    pub Amax_exp: *mut ulong,
    pub Amin_exp: *mut ulong,
    pub Astride: *mut ulong,
    pub Adeflate_deg: *mut slong,
    pub Alead_count: *mut slong,
    pub Atail_count: *mut slong,
    pub Bmax_exp: *mut ulong,
    pub Bmin_exp: *mut ulong,
    pub Bstride: *mut ulong,
    pub Bdeflate_deg: *mut slong,
    pub Blead_count: *mut slong,
    pub Btail_count: *mut slong,
    pub Gmin_exp: *mut ulong,
    pub Abarmin_exp: *mut ulong,
    pub Bbarmin_exp: *mut ulong,
    pub Gstride: *mut ulong,
    pub Gterm_count_est: *mut slong,
    pub Gdeflate_deg_bound: *mut slong,
    pub Gbits: flint_bitcnt_t,
    pub Abarbits: flint_bitcnt_t,
    pub Bbarbits: flint_bitcnt_t,
    pub mvars: slong,
    pub Adeflate_tdeg: slong,
    pub Bdeflate_tdeg: slong,
    pub Adensity: f64,
    pub Bdensity: f64,
    pub hensel_time: f64,
    pub brown_time: f64,
    pub zippel_time: f64,
    pub zippel2_time: f64,
    pub hensel_perm: *mut slong,
    pub brown_perm: *mut slong,
    pub zippel_perm: *mut slong,
    pub zippel2_perm: *mut slong,
    pub can_use: ::std::os::raw::c_uint,
    pub Gdeflate_deg_bounds_are_nice: ::std::os::raw::c_int,
    pub data: *mut ::std::os::raw::c_char,
}
pub type mpoly_gcd_info_t = [mpoly_gcd_info_struct; 1usize];
#[repr(C)]
pub struct mpoly_compression_struct {
    pub mvars: slong,
    pub nvars: slong,
    pub exps: *mut slong,
    pub exps_alloc: slong,
    pub rest: *mut slong,
    pub rest_alloc: slong,
    pub umat: *mut slong,
    pub deltas: *mut slong,
    pub degs: *mut slong,
    pub is_trivial: ::std::os::raw::c_int,
    pub is_perm: ::std::os::raw::c_int,
    pub is_irred: ::std::os::raw::c_int,
}
pub type mpoly_compression_t = [mpoly_compression_struct; 1usize];
#[repr(C)]
pub struct nmod_mpolyn_struct {
    pub coeffs: *mut n_poly_struct,
    pub exps: *mut ulong,
    pub alloc: slong,
    pub length: slong,
    pub bits: slong,
}
pub type nmod_mpolyn_t = [nmod_mpolyn_struct; 1usize];
#[repr(C)]
pub struct nmod_mpolyun_struct {
    pub coeffs: *mut nmod_mpolyn_struct,
    pub exps: *mut ulong,
    pub alloc: slong,
    pub length: slong,
    pub bits: flint_bitcnt_t,
}
pub type nmod_mpolyun_t = [nmod_mpolyun_struct; 1usize];
pub const nmod_gcds_ret_t_nmod_gcds_success: nmod_gcds_ret_t = 0;
pub const nmod_gcds_ret_t_nmod_gcds_form_main_degree_too_high: nmod_gcds_ret_t = 1;
pub const nmod_gcds_ret_t_nmod_gcds_form_wrong: nmod_gcds_ret_t = 2;
pub const nmod_gcds_ret_t_nmod_gcds_no_solution: nmod_gcds_ret_t = 3;
pub const nmod_gcds_ret_t_nmod_gcds_scales_not_found: nmod_gcds_ret_t = 4;
pub const nmod_gcds_ret_t_nmod_gcds_eval_point_not_found: nmod_gcds_ret_t = 5;
pub const nmod_gcds_ret_t_nmod_gcds_eval_gcd_deg_too_high: nmod_gcds_ret_t = 6;
pub type nmod_gcds_ret_t = ::std::os::raw::c_uint;
#[repr(C)]
pub struct fmpz_mpoly_univar_struct {
    pub coeffs: *mut fmpz_mpoly_struct,
    pub exps: *mut fmpz,
    pub alloc: slong,
    pub length: slong,
}
pub type fmpz_mpoly_univar_t = [fmpz_mpoly_univar_struct; 1usize];
#[repr(C)]
pub struct fmpz_mpolyd_struct {
    pub nvars: slong,
    pub degb_alloc: slong,
    pub deg_bounds: *mut slong,
    pub length: slong,
    pub coeff_alloc: slong,
    pub coeffs: *mut fmpz,
}
pub type fmpz_mpolyd_t = [fmpz_mpolyd_struct; 1usize];
#[repr(C)]
pub struct fmpz_mpoly_vec_struct {
    pub p: *mut fmpz_mpoly_struct,
    pub alloc: slong,
    pub length: slong,
}
pub type fmpz_mpoly_vec_t = [fmpz_mpoly_vec_struct; 1usize];
#[repr(C)]
pub struct _fmpz_mpoly_stripe_struct {
    pub big_mem: *mut ::std::os::raw::c_char,
    pub big_mem_alloc: slong,
    pub N: slong,
    pub bits: flint_bitcnt_t,
    pub cmpmask: *const ulong,
    pub startidx: *mut slong,
    pub endidx: *mut slong,
    pub emin: *mut ulong,
    pub emax: *mut ulong,
    pub coeff_bits: flint_bitcnt_t,
    pub upperclosed: ::std::os::raw::c_int,
    pub flint_small: ::std::os::raw::c_int,
}
pub type fmpz_mpoly_stripe_struct = _fmpz_mpoly_stripe_struct;
pub type fmpz_mpoly_stripe_t = [fmpz_mpoly_stripe_struct; 1usize];
#[repr(C)]
pub struct fmpz_mpolyd_ctx_struct {
    pub nvars: slong,
    pub perm: *mut slong,
}
pub type fmpz_mpolyd_ctx_t = [fmpz_mpolyd_ctx_struct; 1usize];
#[repr(C)]
pub struct _bindgen_ty_3 {
    pub powers: *mut fmpz,
    pub length: slong,
    pub alloc: slong,
    pub tmp: fmpz_t,
}
pub type fmpz_pow_cache_t = [_bindgen_ty_3; 1usize];
#[repr(C)]
pub struct fmpz_mpoly_geobucket {
    pub polys: [fmpz_mpoly_struct; 32usize],
    pub temps: [fmpz_mpoly_struct; 32usize],
    pub length: slong,
}
pub type fmpz_mpoly_geobucket_struct = fmpz_mpoly_geobucket;
pub type fmpz_mpoly_geobucket_t = [fmpz_mpoly_geobucket_struct; 1usize];
#[repr(C)]
pub struct fmpq_mat_struct {
    pub entries: *mut fmpq,
    pub r: slong,
    pub c: slong,
    pub stride: slong,
}
pub type fmpq_mat_t = [fmpq_mat_struct; 1usize];
#[repr(C)]
pub struct fmpq_poly_struct {
    pub coeffs: *mut fmpz,
    pub alloc: slong,
    pub length: slong,
    pub den: fmpz_t,
}
pub type fmpq_poly_t = [fmpq_poly_struct; 1usize];
#[repr(C)]
pub struct fmpq_mpoly_struct {
    pub content: fmpq_t,
    pub zpoly: fmpz_mpoly_t,
}
pub type fmpq_mpoly_t = [fmpq_mpoly_struct; 1usize];
#[repr(C)]
pub struct fmpq_mpoly_factor_struct {
    pub constant: fmpq_t,
    pub poly: *mut fmpq_mpoly_struct,
    pub exp: *mut fmpz,
    pub num: slong,
    pub alloc: slong,
}
pub type fmpq_mpoly_factor_t = [fmpq_mpoly_factor_struct; 1usize];
#[repr(C)]
pub struct qqbar_struct {
    pub poly: fmpz_poly_struct,
    pub enclosure: acb_struct,
}
pub type qqbar_t = [qqbar_struct; 1usize];
pub type qqbar_ptr = *mut qqbar_struct;
pub type qqbar_srcptr = *const qqbar_struct;
#[repr(C)]
pub struct fmpz_poly_powers_precomp_struct {
    pub powers: *mut *mut fmpz,
    pub len: slong,
}
pub type fmpz_poly_powers_precomp_t = [fmpz_poly_powers_precomp_struct; 1usize];
#[repr(C)]
pub struct fmpz_poly_mul_precache_struct {
    pub jj: *mut *mut ulong,
    pub n: slong,
    pub len2: slong,
    pub loglen: slong,
    pub bits2: slong,
    pub limbs: slong,
    pub poly2: fmpz_poly_t,
}
pub type fmpz_poly_mul_precache_t = [fmpz_poly_mul_precache_struct; 1usize];
#[repr(C)]
pub struct fmpq_poly_powers_precomp_struct {
    pub powers: *mut fmpq_poly_struct,
    pub len: slong,
}
pub type fmpq_poly_powers_precomp_t = [fmpq_poly_powers_precomp_struct; 1usize];
#[repr(C)]
pub struct nf_struct {
    pub pol: fmpq_poly_t,
    pub pinv: nf_struct__bindgen_ty_1,
    pub powers: nf_struct__bindgen_ty_2,
    pub traces: fmpq_poly_t,
    pub flag: ulong,
}
#[repr(C)]
pub struct nf_struct__bindgen_ty_1 {
    pub qq: __BindgenUnionField<fmpz_preinvn_t>,
    pub bindgen_union_field: [u64; 3usize],
}
#[repr(C)]
pub struct nf_struct__bindgen_ty_2 {
    pub qq: __BindgenUnionField<fmpq_poly_powers_precomp_t>,
    pub zz: __BindgenUnionField<fmpz_poly_powers_precomp_t>,
    pub bindgen_union_field: [u64; 2usize],
}
pub type nf_t = [nf_struct; 1usize];
#[repr(C)]
pub struct lnf_elem_struct {
    pub num: fmpz_t,
    pub den: fmpz_t,
}
pub type lnf_elem_t = [lnf_elem_struct; 1usize];
#[repr(C)]
pub struct qnf_elem_struct {
    pub num: [fmpz; 3usize],
    pub den: fmpz_t,
}
pub type qnf_elem_t = [qnf_elem_struct; 1usize];
#[repr(C)]
pub struct nf_elem_struct {
    pub elem: __BindgenUnionField<fmpq_poly_t>,
    pub lelem: __BindgenUnionField<lnf_elem_t>,
    pub qelem: __BindgenUnionField<qnf_elem_t>,
    pub bindgen_union_field: [u64; 4usize],
}
pub type nf_elem_t = [nf_elem_struct; 1usize];
pub const calcium_func_code_CA_QQBar: calcium_func_code = 0;
pub const calcium_func_code_CA_Neg: calcium_func_code = 1;
pub const calcium_func_code_CA_Add: calcium_func_code = 2;
pub const calcium_func_code_CA_Sub: calcium_func_code = 3;
pub const calcium_func_code_CA_Mul: calcium_func_code = 4;
pub const calcium_func_code_CA_Div: calcium_func_code = 5;
pub const calcium_func_code_CA_Sqrt: calcium_func_code = 6;
pub const calcium_func_code_CA_Cbrt: calcium_func_code = 7;
pub const calcium_func_code_CA_Root: calcium_func_code = 8;
pub const calcium_func_code_CA_Floor: calcium_func_code = 9;
pub const calcium_func_code_CA_Ceil: calcium_func_code = 10;
pub const calcium_func_code_CA_Abs: calcium_func_code = 11;
pub const calcium_func_code_CA_Sign: calcium_func_code = 12;
pub const calcium_func_code_CA_Re: calcium_func_code = 13;
pub const calcium_func_code_CA_Im: calcium_func_code = 14;
pub const calcium_func_code_CA_Arg: calcium_func_code = 15;
pub const calcium_func_code_CA_Conjugate: calcium_func_code = 16;
pub const calcium_func_code_CA_Pi: calcium_func_code = 17;
pub const calcium_func_code_CA_Sin: calcium_func_code = 18;
pub const calcium_func_code_CA_Cos: calcium_func_code = 19;
pub const calcium_func_code_CA_Exp: calcium_func_code = 20;
pub const calcium_func_code_CA_Log: calcium_func_code = 21;
pub const calcium_func_code_CA_Pow: calcium_func_code = 22;
pub const calcium_func_code_CA_Tan: calcium_func_code = 23;
pub const calcium_func_code_CA_Cot: calcium_func_code = 24;
pub const calcium_func_code_CA_Cosh: calcium_func_code = 25;
pub const calcium_func_code_CA_Sinh: calcium_func_code = 26;
pub const calcium_func_code_CA_Tanh: calcium_func_code = 27;
pub const calcium_func_code_CA_Coth: calcium_func_code = 28;
pub const calcium_func_code_CA_Atan: calcium_func_code = 29;
pub const calcium_func_code_CA_Acos: calcium_func_code = 30;
pub const calcium_func_code_CA_Asin: calcium_func_code = 31;
pub const calcium_func_code_CA_Acot: calcium_func_code = 32;
pub const calcium_func_code_CA_Atanh: calcium_func_code = 33;
pub const calcium_func_code_CA_Acosh: calcium_func_code = 34;
pub const calcium_func_code_CA_Asinh: calcium_func_code = 35;
pub const calcium_func_code_CA_Acoth: calcium_func_code = 36;
pub const calcium_func_code_CA_Euler: calcium_func_code = 37;
pub const calcium_func_code_CA_Gamma: calcium_func_code = 38;
pub const calcium_func_code_CA_LogGamma: calcium_func_code = 39;
pub const calcium_func_code_CA_Psi: calcium_func_code = 40;
pub const calcium_func_code_CA_Erf: calcium_func_code = 41;
pub const calcium_func_code_CA_Erfc: calcium_func_code = 42;
pub const calcium_func_code_CA_Erfi: calcium_func_code = 43;
pub const calcium_func_code_CA_RiemannZeta: calcium_func_code = 44;
pub const calcium_func_code_CA_HurwitzZeta: calcium_func_code = 45;
pub const calcium_func_code_CA_FUNC_CODE_LENGTH: calcium_func_code = 46;
pub type calcium_func_code = ::std::os::raw::c_uint;
#[repr(C)]
pub struct ca_elem_struct {
    pub q: __BindgenUnionField<fmpq>,
    pub nf: __BindgenUnionField<nf_elem_struct>,
    pub mpoly_q: __BindgenUnionField<*mut fmpz_mpoly_q_struct>,
    pub bindgen_union_field: [u64; 4usize],
}
#[repr(C)]
pub struct ca_struct {
    pub field: ulong,
    pub elem: ca_elem_struct,
}
pub type ca_t = [ca_struct; 1usize];
pub type ca_ptr = *mut ca_struct;
pub type ca_srcptr = *const ca_struct;
#[repr(C)]
pub struct ca_ext_qqbar {
    pub x: qqbar_struct,
    pub nf: *mut nf_struct,
}
#[repr(C)]
pub struct ca_ext_func_data {
    pub args: *mut ca_struct,
    pub nargs: slong,
    pub enclosure: acb_struct,
    pub prec: slong,
    pub qqbar: *mut qqbar_struct,
}
#[repr(C)]
pub struct ca_ext_struct {
    pub head: calcium_func_code,
    pub hash: ulong,
    pub depth: slong,
    pub data: ca_ext_struct__bindgen_ty_1,
}
#[repr(C)]
pub struct ca_ext_struct__bindgen_ty_1 {
    pub qqbar: __BindgenUnionField<ca_ext_qqbar>,
    pub func_data: __BindgenUnionField<ca_ext_func_data>,
    pub bindgen_union_field: [u64; 16usize],
}
pub type ca_ext_t = [ca_ext_struct; 1usize];
pub type ca_ext_ptr = *mut ca_ext_struct;
pub type ca_ext_srcptr = *const ca_ext_struct;
#[repr(C)]
pub struct ca_ext_cache_struct {
    pub items: *mut *mut ca_ext_struct,
    pub length: slong,
    pub alloc: slong,
    pub hash_size: slong,
    pub hash_table: *mut slong,
}
pub type ca_ext_cache_t = [ca_ext_cache_struct; 1usize];
#[repr(C)]
pub struct ca_field_struct {
    pub length: slong,
    pub ext: *mut *mut ca_ext_struct,
    pub ideal: fmpz_mpoly_vec_struct,
    pub hash: ulong,
}
pub type ca_field_t = [ca_field_struct; 1usize];
pub type ca_field_ptr = *mut ca_field_struct;
pub type ca_field_srcptr = *const ca_field_struct;
#[repr(C)]
pub struct ca_field_cache_struct {
    pub items: *mut *mut ca_field_struct,
    pub length: slong,
    pub alloc: slong,
    pub hash_size: slong,
    pub hash_table: *mut slong,
}
pub type ca_field_cache_t = [ca_field_cache_struct; 1usize];
#[repr(C)]
pub struct ca_ctx_struct {
    pub ext_cache: ca_ext_cache_struct,
    pub field_cache: ca_field_cache_struct,
    pub field_qq: *mut ca_field_struct,
    pub field_qq_i: *mut ca_field_struct,
    pub mctx: *mut *mut fmpz_mpoly_ctx_struct,
    pub mctx_len: slong,
    pub options: *mut slong,
}
pub type ca_ctx_t = [ca_ctx_struct; 1usize];
#[repr(C)]
pub struct ca_factor_struct {
    pub base: ca_ptr,
    pub exp: ca_ptr,
    pub length: slong,
    pub alloc: slong,
}
pub type ca_factor_t = [ca_factor_struct; 1usize];
#[repr(C)]
pub struct ca_vec_struct {
    pub entries: ca_ptr,
    pub alloc: slong,
    pub length: slong,
}
pub type ca_vec_t = [ca_vec_struct; 1usize];
#[repr(C)]
pub struct ca_mat_struct {
    pub entries: ca_ptr,
    pub r: slong,
    pub c: slong,
    pub stride: slong,
}
pub type ca_mat_t = [ca_mat_struct; 1usize];
#[repr(C)]
pub struct ca_poly_struct {
    pub coeffs: *mut ca_struct,
    pub alloc: slong,
    pub length: slong,
}
pub type ca_poly_t = [ca_poly_struct; 1usize];
pub type fq_t = fmpz_poly_t;
pub type fq_struct = fmpz_poly_struct;
#[repr(C)]
pub struct fq_ctx_struct {
    pub ctxp: fmpz_mod_ctx_t,
    pub sparse_modulus: ::std::os::raw::c_int,
    pub is_conway: ::std::os::raw::c_int,
    pub a: *mut fmpz,
    pub j: *mut slong,
    pub len: slong,
    pub modulus: fmpz_mod_poly_t,
    pub inv: fmpz_mod_poly_t,
    pub var: *mut ::std::os::raw::c_char,
}
pub type fq_ctx_t = [fq_ctx_struct; 1usize];
#[repr(C)]
pub struct fq_mat_struct {
    pub entries: *mut fq_struct,
    pub r: slong,
    pub c: slong,
    pub stride: slong,
}
pub type fq_mat_t = [fq_mat_struct; 1usize];
#[repr(C)]
pub struct fq_poly_struct {
    pub coeffs: *mut fq_struct,
    pub alloc: slong,
    pub length: slong,
}
pub type fq_poly_t = [fq_poly_struct; 1usize];
#[repr(C)]
pub struct fq_poly_factor_struct {
    pub poly: *mut fq_poly_struct,
    pub exp: *mut slong,
    pub num: slong,
    pub alloc: slong,
}
pub type fq_poly_factor_t = [fq_poly_factor_struct; 1usize];
#[repr(C)]
pub struct fq_zech_struct {
    pub value: ulong,
}
pub type fq_zech_t = [fq_zech_struct; 1usize];
#[repr(C)]
pub struct fq_zech_ctx_struct {
    pub qm1: ulong,
    pub qm1o2: ulong,
    pub qm1opm1: ulong,
    pub p: ulong,
    pub ppre: f64,
    pub prime_root: ulong,
    pub zech_log_table: *mut ulong,
    pub prime_field_table: *mut ulong,
    pub eval_table: *mut ulong,
    pub fq_nmod_ctx: *mut fq_nmod_ctx_struct,
    pub owns_fq_nmod_ctx: ::std::os::raw::c_int,
    pub is_conway: ::std::os::raw::c_int,
}
pub type fq_zech_ctx_t = [fq_zech_ctx_struct; 1usize];
#[repr(C)]
pub struct fq_zech_mat_struct {
    pub entries: *mut fq_zech_struct,
    pub r: slong,
    pub c: slong,
    pub stride: slong,
}
pub type fq_zech_mat_t = [fq_zech_mat_struct; 1usize];
#[repr(C)]
pub struct fq_zech_poly_struct {
    pub coeffs: *mut fq_zech_struct,
    pub alloc: slong,
    pub length: slong,
}
pub type fq_zech_poly_t = [fq_zech_poly_struct; 1usize];
#[repr(C)]
pub struct fq_zech_poly_factor_struct {
    pub poly: *mut fq_zech_poly_struct,
    pub exp: *mut slong,
    pub num: slong,
    pub alloc: slong,
}
pub type fq_zech_poly_factor_t = [fq_zech_poly_factor_struct; 1usize];
#[repr(C)]
pub struct n_factor_t {
    pub num: ::std::os::raw::c_int,
    pub exp: [::std::os::raw::c_int; 15usize],
    pub p: [ulong; 15usize],
}
#[repr(C)]
pub struct n_primes_struct {
    pub small_i: slong,
    pub small_num: slong,
    pub small_primes: *mut ::std::os::raw::c_uint,
    pub sieve_a: ulong,
    pub sieve_b: ulong,
    pub sieve_i: slong,
    pub sieve_num: slong,
    pub sieve: *mut ::std::os::raw::c_char,
}
pub type n_primes_t = [n_primes_struct; 1usize];
#[repr(C)]
pub struct padic_struct {
    pub u: fmpz,
    pub v: slong,
    pub N: slong,
}
pub type padic_t = [padic_struct; 1usize];
pub const padic_print_mode_PADIC_TERSE: padic_print_mode = 0;
pub const padic_print_mode_PADIC_SERIES: padic_print_mode = 1;
pub const padic_print_mode_PADIC_VAL_UNIT: padic_print_mode = 2;
pub type padic_print_mode = ::std::os::raw::c_uint;
#[repr(C)]
pub struct padic_ctx_struct {
    pub p: fmpz_t,
    pub pinv: f64,
    pub pow: *mut fmpz,
    pub min: slong,
    pub max: slong,
    pub mode: padic_print_mode,
}
pub type padic_ctx_t = [padic_ctx_struct; 1usize];
#[repr(C)]
pub struct padic_inv_struct {
    pub n: slong,
    pub pow: *mut fmpz,
}
pub type padic_inv_t = [padic_inv_struct; 1usize];
#[repr(C)]
pub struct padic_mat_struct {
    pub mat: fmpz_mat_struct,
    pub val: slong,
    pub N: slong,
}
pub type padic_mat_t = [padic_mat_struct; 1usize];
#[repr(C)]
pub struct padic_poly_struct {
    pub coeffs: *mut fmpz,
    pub alloc: slong,
    pub length: slong,
    pub val: slong,
    pub N: slong,
}
pub type padic_poly_t = [padic_poly_struct; 1usize];
